import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync, rmSync, mkdirSync, statSync, utimesSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { observeRepository, observeRepositoryAsync } from '../bin/observation.mjs';
import { createMcpHandler } from '../bin/mcp.mjs';
function fixture(t) {
    const root = realpathSync(mkdtempSync(join(tmpdir(), 'lattice-mcp-fresh-')));
    t.after(() => rmSync(root, { recursive: true, force: true }));
    execFileSync('git', ['init', '-q', root]);
    writeFileSync(join(root, '.gitignore'), '.lattice/cache/\n');
    writeFileSync(join(root, 'data.json'), JSON.stringify([{ id: 'one', name: 'Alpha' }, { id: 'two', name: 'Bravo', targetId: 'one' }]));
    execFileSync('git', ['-C', root, 'add', '.']);
    execFileSync('git', ['-C', root, '-c', 'user.name=Test', '-c', 'user.email=test@example.invalid', 'commit', '-qm', 'fixture']);
    return { root, call: createMcpHandler({ root }) };
}
test('all queries content-check, reuse unchanged graph and see same-size preserved-mtime edits', async t => {
    const f = fixture(t), first = await f.call('lattice_find', {}), unchanged = await f.call('lattice_freshness', {});
    assert.equal((await observeRepositoryAsync({ root: f.root })).fingerprint, observeRepository({ root: f.root }).fingerprint);
    assert.equal(first.freshness.rebuilt, true); assert.equal(unchanged.freshness.rebuilt, false);
    assert.equal(first.graphHash, unchanged.graphHash);
    const path = join(f.root, 'data.json'), stat = statSync(path);
    writeFileSync(path, readFileSync(path, 'utf8').replace('Alpha', 'Omega'));
    utimesSync(path, stat.atime, stat.mtime);
    const changed = await f.call('lattice_find', { q: 'Omega' });
    assert.equal(changed.freshness.rebuilt, true); assert.equal(changed.total, 1);
    assert.notEqual(changed.graphHash, first.graphHash);
    const difference = await f.call('lattice_diff', { ref: 'HEAD' });
    assert.equal(difference.link, null);
    assert.equal(difference.nodes.changed.items.find(change => change.after.id === 'one').after.name, 'Omega');
    assert.equal(difference.nodes.changed.total, 1);
    const added = join(f.root, 'new.json');
    writeFileSync(added, JSON.stringify([{ id: 'three', name: 'Added' }]));
    assert.equal((await f.call('lattice_find', { q: 'Added' })).total, 1);
    rmSync(added);
    assert.equal((await f.call('lattice_find', { q: 'Added' })).total, 0);
});
test('lens parse failure never returns previous graph; corrected lens recovers', async t => {
    const f = fixture(t); await f.call('lattice_overview', {});
    mkdirSync(join(f.root, '.lattice'), { recursive: true });
    writeFileSync(join(f.root, '.lattice/lens.yaml'), 'schemaVersion: [');
    await assert.rejects(() => f.call('lattice_overview', {}));
    rmSync(join(f.root, '.lattice/lens.yaml'));
    assert.equal((await f.call('lattice_overview', {})).freshness.status, 'fresh');
    const path = join(f.root, '.lattice/lens.json');
    writeFileSync(path, JSON.stringify({ schemaVersion: 1, name: 'Lens', kinds: [{ id: 'thing', label: 'Things', files: ['data.json'] }] }));
    assert.equal((await f.call('lattice_find', { kind: 'thing' })).total, 2);
    const stat = statSync(path);
    writeFileSync(path, readFileSync(path, 'utf8').replace('thing', 'other'));
    utimesSync(path, stat.atime, stat.mtime);
    assert.equal((await f.call('lattice_find', { kind: 'other' })).total, 2);
    assert.equal((await f.call('lattice_find', { kind: 'thing' })).total, 0);
});
