/** Attribution, license notices and URLs are evidence, not statements of a module's purpose. */
export function descriptiveProse(value: string): boolean {
    const text = value.trim();
    if (/^(?:<auto-generated>|(?:(?:this|the)\s+)?(?:file|code)\s+(?:(?:was|is)\s+)?(?:automatically\s+)?generated\b|automatically generated\b|generated by (?:a |the )?tool\b)/iu.test(text)) return false;
    if (/^(?:internal\s+)?(?:apis?(?:\s+(?:functions?|interfaces?))?|functions?|interfaces?)\s*[(:—-]?\s*(?:are\s+|is\s+)?subject to change(?: without notice)?[).!\s]*(?:[^.!?]*\bpin\b[^.!?]*\bversion\b[.!\s]*)?$/iu.test(text)) return false;
    if (/copyright|spdx-license|licensed under|all rights reserved|permission is hereby granted|\b(?:MIT|ISC|BSD|Apache|GPL|Mozilla)\s+Licen[cs]e\b|©/iu.test(text)) return false;
    if (/^(?:(?:the\s+)?(?:original\s+)?(?:work|code|implementation)\s+(?:was|is)\s+)?(?:ported|inlined|adapted|copied|derived|borrowed)\s+from\b|^(?:source|upstream|reference):\s*https?:/iu.test(text)) return false;
    return /\p{L}/u.test(text.replace(/https?:\/\/\S+/gu, "").replace(/\[[^\]]*\]\([^)]*\)/gu, ""));
}
