import type { Node as GraphNode, Edge } from '../dist/core/model.js';
import { filterGraph, shortestPath, neighborhood, groupGraph, rankHubs } from './explore-model.js';
import { canvas, type CanvasNode, type CanvasEdge } from './explore-canvas.js';
import { controls, element, action, anchor, route, pager, pageNumber, type ExploreContext } from './explore-controls.js';

export function renderExplore(container: HTMLElement, context: ExploreContext): (() => void) | undefined {
    controls(container, context); const { params } = context;
    const graph = filterGraph(context.nodes, context.edges, context.facets, Object.fromEntries(['kind', 'edgeKind', 'facet', 'value', 'q'].filter(key => params.get(key)).map(key => [key, params.get(key) ?? ''])));
    let projection = graph; let explanation = '';
    if (params.get('mode') === 'path') { const path = shortestPath(graph.nodes, graph.edges, params.get('from') ?? '', params.get('to') ?? ''); const ids = new Set(path?.nodeIds); const edges = new Set(path?.edgeIds); projection = { nodes: graph.nodes.filter(node => ids.has(node.id)), edges: graph.edges.filter(edge => edges.has(edge.id)) }; explanation = path ? `최단 경로: ${path.nodeIds.length}개 노드 · ${path.edgeIds.length}개 관계` : '경로 없음: 시작·도착 ID, 필터와 관계 방향을 확인하세요.'; }
    if (params.get('mode') === 'neighbors') { const from = params.get('from') ?? ''; const direction = params.get('direction'); projection = neighborhood(graph.nodes, graph.edges, from, Number(params.get('hops') ?? 1), direction === 'in' || direction === 'both' ? direction : 'out'); explanation = graph.nodes.some(node => node.id === from) ? `영향 범위: ${projection.nodes.length}개 노드 · ${projection.edges.length}개 관계` : '시작 노드 없음: ID와 현재 필터를 확인하세요.'; }
    const summary = element('p', `필터 결과 ${graph.nodes.length} / ${context.nodes.length}개 노드 · ${graph.edges.length}개 관계${explanation ? ` · ${explanation}` : ''}`, 'explore-summary'); summary.setAttribute('role', 'status'); container.append(summary);
    if (!projection.nodes.length) { container.append(element('p', context.nodes.length ? '표시할 노드가 없습니다. 필터 또는 탐색 조건을 바꿔 주세요.' : '이 층에 노드가 없습니다.', 'empty')); return; }
    const by = params.get('group') === 'folder' ? 'folder' : 'kind'; const grouped = groupGraph(projection.nodes, projection.edges, by); const aggregate = projection.nodes.length > 50;
    const groupPage = pageNumber(params.get('groupPage'), grouped.groups.length, 24); const visibleGroups = grouped.groups.slice(groupPage * 24, (groupPage + 1) * 24);
    const groupEdges = new Map<string, number>(); for (const link of grouped.links) { groupEdges.set(link.source, (groupEdges.get(link.source) ?? 0) + link.count); groupEdges.set(link.target, (groupEdges.get(link.target) ?? 0) + link.count); }
    const expanded = grouped.groups.find(group => group.id === params.get('expanded')); const nodePage = pageNumber(params.get('nodePage'), expanded?.nodeIds.length ?? projection.nodes.length, 50);
    const nodeMap = new Map(projection.nodes.map(node => [node.id, node])); const memberIds = expanded ? expanded.nodeIds : projection.nodes.map(node => node.id); const pageIds = memberIds.slice(nodePage * 50, (nodePage + 1) * 50);
    const pins = new Set(params.has('pin') ? params.getAll('pin').flatMap(value => value.split('\n')).filter(Boolean) : projection.nodes.filter(node => node.attributes['pinned'] === true).map(node => node.id)); const selected = params.get('selected') ?? '';
    const facets = new Map<string, string[]>(); for (const facet of context.facets) { const items = facets.get(facet.nodeId) ?? []; items.push(`${context.facetLabel(facet.key)}: ${context.valueLabel(facet.key, facet.value)}`); facets.set(facet.nodeId, items); }
    const chosenFacet = params.get('facet') || [...new Set(context.facets.map(facet => facet.key))].sort()[0] || ''; const facetValues = new Map(context.facets.filter(facet => facet.key === chosenFacet).map(facet => [facet.nodeId, `${context.facetLabel(facet.key)}: ${context.valueLabel(facet.key, facet.value)}`]));
    const toCanvas = (node: GraphNode): CanvasNode => ({ id: node.id, label: node.name, kind: node.kind, count: 1, cluster: false, facet: (facets.get(node.id) ?? []).join(' · '), pinned: pins.has(node.id), facetValue: facetValues.get(node.id) ?? '' });
    const shownNodes = aggregate ? [...new Set([...pins, ...(expanded ? pageIds : [])])].flatMap(id => { const node = nodeMap.get(id); return node ? [node] : []; }).slice(0, 50) : projection.nodes;
    if (aggregate && pins.size) container.append(element('p', `고정 ${pins.size}개 · 펼친 노드와 함께 지도 최대 50개를 표시합니다. 전체 고정 노드는 검색과 목록으로 확인할 수 있습니다.`, 'meta'));
    const shownIds = new Set(shownNodes.map(node => node.id)); const displayNodes: CanvasNode[] = shownNodes.map(toCanvas); const endpoint = new Map(shownNodes.map(node => [node.id, node.id]));
    if (aggregate) for (const group of visibleGroups) { const remaining = group.nodeIds.filter(id => !shownIds.has(id)); if (remaining.length) displayNodes.push({ id: group.id, label: by === 'kind' ? context.kindLabel(group.label) : group.label, kind: by === 'kind' ? group.label : 'folder', count: remaining.length, cluster: true, facet: '', pinned: false, facetValue: '' }); for (const id of remaining) endpoint.set(id, group.id); }
    const displayEdges = new Map<string, CanvasEdge>(); for (const edge of projection.edges) { const source = endpoint.get(edge.source); const target = endpoint.get(edge.target); if (!source || !target) continue; const label = typeof edge.attributes?.['label'] === 'string' ? edge.attributes['label'] : edge.kind; const key = JSON.stringify([source, target, edge.kind, edge.directed, label]); const previous = displayEdges.get(key); displayEdges.set(key, { source, target, label, directed: edge.directed, count: (previous?.count ?? 0) + 1 }); }
    const go = (changes: Record<string, string>) => { location.hash = route(context, changes); };
    const choose = (id: string) => { if (grouped.groups.some(group => group.id === id)) go({ expanded: id, nodePage: '0', selected: '' }); else go({ selected: id, focus: '' }); };
    if (aggregate) container.append(element('p', `50개 초과: ${grouped.groups.length}개 그룹으로 묶었습니다. 지도에는 그룹 최대 24개, 펼친 노드 최대 50개를 표시합니다. 나머지는 그룹·노드 목록의 페이지로 모두 탐색할 수 있습니다.`, 'meta'));
    const dispose = canvas(container, { nodes: displayNodes, edges: [...displayEdges.values()], kinds: [...new Set([...context.nodes.map(node => node.kind), ...(by === 'folder' ? ['folder'] : [])])].sort(), kindLabel: context.kindLabel, selected, choose });
    if (aggregate) {
        const section = element('section', '', 'panel section'); section.append(element('h2', `그룹 ${grouped.groups.length}개`));
        for (const group of visibleGroups) { const row = element('div', '', 'count-row explore-group-row'); row.append(anchor(by === 'kind' ? context.kindLabel(group.label) : group.label, route(context, { expanded: group.id, nodePage: '0', selected: '' })), element('span', `${group.nodeIds.length}개 노드 · 내부 관계 ${group.internalEdges}개 · 외부 관계 ${groupEdges.get(group.id) ?? 0}개`, 'mono')); section.append(row); }
        pager(section, { total: grouped.groups.length, page: groupPage, size: 24, change: page => go({ groupPage: String(page) }) }); container.append(section);
    }
    const inspector = element('section', '', 'panel section explore-inspector'); const chosen = nodeMap.get(selected);
    if (chosen) { inspector.tabIndex = -1; inspector.setAttribute('aria-label', `선택한 노드 ${chosen.name}`); inspector.append(element('h2', chosen.name), element('code', chosen.id), element('p', context.kindLabel(chosen.kind))); for (const item of facets.get(chosen.id) ?? []) inspector.append(element('p', item, 'meta')); const actions = element('div', '', 'actions'); actions.append(anchor('노드 상세', context.nodeHref(chosen.id)), action('선택 닫기', () => go({ selected: '', focus: chosen.id }))); inspector.append(actions); const sources = element('ul', '', 'sources'); for (const source of chosen.sources) { const row = element('li'); const text = `${source.path}:${source.line} ${source.pointer}`; if (source.url && /^https?:\/\//.test(source.url)) row.append(anchor(text, source.url)); else row.append(element('span', text + ' · 로컬 출처')); sources.append(row); } inspector.append(sources); renderRelations(inspector, context, projection.edges.filter(edge => edge.source === selected || edge.target === selected), nodeMap, 'relationPage'); inspector.onkeydown = event => { if (event.key === 'Escape') { event.preventDefault(); go({ selected: '', focus: chosen.id }); } }; container.append(inspector); requestAnimationFrame(() => inspector.focus()); }
    const nodes = element('section', '', 'panel section'); nodes.append(element('h2', expanded ? `펼친 그룹: ${by === 'kind' ? context.kindLabel(expanded.label) : expanded.label}` : '전체 노드 목록'));
    if (expanded) nodes.append(anchor('그룹 접기', route(context, { expanded: '', nodePage: '0' })));
    for (const id of pageIds) { const node = nodeMap.get(id); if (!node) continue; const row = element('div', '', 'explore-node-row'); const inspect = action(node.name, () => choose(id)); inspect.dataset['nodeId'] = id; row.append(inspect, element('code', id), element('span', context.kindLabel(node.kind), 'meta')); const actions = element('div', '', 'actions'); actions.append(anchor('시작', route(context, { from: id })), anchor('도착', route(context, { to: id })), anchor(pins.has(id) ? '고정 해제' : '고정', route(context, { pin: [...pins].filter(pin => pin !== id).concat(pins.has(id) ? [] : [id]).join('\n') })), anchor('상세', context.nodeHref(id))); row.append(actions); nodes.append(row); }
    pager(nodes, { total: memberIds.length, page: nodePage, size: 50, change: page => go({ nodePage: String(page) }) }); container.append(nodes);
    const hubs = element('details', '', 'panel section'); hubs.open = params.has('hubPage'); hubs.append(element('summary', '연결 중심 노드')); const ranked = rankHubs(projection.nodes, projection.edges); const hubPage = pageNumber(params.get('hubPage'), ranked.length, 20); for (const hub of ranked.slice(hubPage * 20, (hubPage + 1) * 20)) { const row = element('div', '', 'count-row'); row.append(anchor(nodeMap.get(hub.id)?.name ?? hub.id, route(context, { selected: hub.id })), element('span', `${hub.degree}개 관계`, 'mono')); hubs.append(row); } pager(hubs, { total: ranked.length, page: hubPage, size: 20, change: page => go({ hubPage: String(page) }) }); container.append(hubs);
    const edges = element('section', '', 'panel section'); edges.append(element('h2', `전체 관계 ${projection.edges.length}개`)); renderRelations(edges, context, projection.edges, nodeMap, 'edgePage'); container.append(edges);
    const focus = params.get('focus'); if (focus && !chosen) requestAnimationFrame(() => { for (const button of container.querySelectorAll<HTMLElement | SVGElement>('[data-node-id]')) if (button.dataset['nodeId'] === focus) { button.focus(); break; } });
    return dispose;
}
function renderRelations(container: HTMLElement, context: ExploreContext, edges: readonly Edge[], nodes: ReadonlyMap<string, GraphNode>, key: string): void {
    const page = pageNumber(context.params.get(key), edges.length, 30); const list = element('ul', '', 'neighbors');
    for (const edge of edges.slice(page * 30, (page + 1) * 30)) { const item = element('li'); item.append(anchor(nodes.get(edge.source)?.name ?? edge.source, context.nodeHref(edge.source)), document.createTextNode(` ${edge.directed ? '→' : '↔'} `), anchor(nodes.get(edge.target)?.name ?? edge.target, context.nodeHref(edge.target)), element('span', ` · ${typeof edge.attributes?.['label'] === 'string' ? edge.attributes['label'] : edge.kind} [${edge.kind}]`)); list.append(item); }
    container.append(list); pager(container, { total: edges.length, page, size: 30, change: next => { location.hash = route(context, { [key]: String(next) }); } });
}
