import type { LoopNode, LoopUI } from './loop-map-types.js';
import { anchor, chip, element, glyph, interpretation, kindLabel, label, liveDot, media, orderedKinds, svg } from './loop-map-shared.js';

export function createFocusView(host: HTMLElement, ui: LoopUI): { readonly select: (id: string) => void; readonly cleanup: () => void; } {
    const layout = element('div', '', 'lm-focus'); const finder = element('aside', '', 'lm-finder'); finder.setAttribute('aria-label', '항목 찾기');
    const searchLabel = element('label', '이름으로 찾기'); const search = element('input'); search.type = 'search'; search.placeholder = '이름·문구로 찾기'; searchLabel.append(search);
    const kindCaption = element('label', '종류'); const kind = element('select'); const all = element('option', `전체 ${ui.model.nodes.length}`); all.value = ''; kind.append(all);
    for (const value of orderedKinds(ui)) { const nodes = ui.model.nodes.filter(node => node.kind === value); const option = element('option', `${kindLabel(value, ui)} ${nodes.length}`); option.value = value; kind.append(option); } kindCaption.append(kind);
    const list = element('ul', '', 'lm-finder-list'); finder.append(searchLabel, kindCaption, list); const main = element('article', '', 'lm-focus-main'); main.setAttribute('aria-live', 'polite'); layout.append(finder, main); host.append(layout); let active: LoopNode | undefined; let draw = (): void => { };
    const renderList = (): void => {
        list.replaceChildren(); const query = search.value.trim().toLocaleLowerCase(); for (const value of orderedKinds(ui)) {
            if (kind.value && kind.value !== value) continue; const nodes = ui.model.nodes.filter(node => node.kind === value && (!query || `${node.name} ${node.summary}`.toLocaleLowerCase().includes(query))); if (!nodes.length) continue; list.append(element('li', `${kindLabel(value, ui)} ${nodes.length}`, 'lm-finder-separator'));
            for (const node of nodes) { const li = element('li'); const button = element('button', '', 'lm-finder-item'); button.type = 'button'; button.dataset['node'] = node.id; button.setAttribute('aria-current', String(active?.id === node.id)); button.append(glyph(node), element('span', node.name)); const dot = liveDot(node, ui); if (dot) button.append(dot); button.onclick = () => ui.openFocus(node.id); li.append(button); list.append(li); }
        } if (!list.childElementCount) list.append(element('li', '찾는 항목이 없습니다', 'lm-finder-separator'));
    };
    search.oninput = renderList; kind.onchange = renderList;
    const select = (id: string): void => {
        const node = ui.byId.get(id); if (!node) return; active = node; renderList(); main.replaceChildren();
        const type = element('div', '', 'lm-kind'); type.append(glyph(node), document.createTextNode(label(node, ui))); const header = element('div', '', 'lm-focus-heading'); header.append(element('h2', node.name)); if (ui.model.nodes.some(item => item.status !== 'unknown')) header.append(element('span', ui.model.statusLabels[node.status], `lm-pill${node.status === 'present' ? ' lm-live' : ''}`)); main.append(type, header, element('p', node.summary, 'lm-card-text')); const asset = media(node); if (asset) main.append(asset);
        const ego = element('div', '', 'lm-ego'); ego.setAttribute('aria-label', `${node.name}과 이어진 콘텐츠`); main.append(ego);
        const full = element('div', '', `lm-relations${node.relationGroups.every(group => group.items.length <= 6) ? ' lm-relations-complete' : ''}`); const relationBlocks: HTMLElement[] = [];
        for (const group of node.relationGroups) { const block = element('section', '', 'lm-group'); block.append(element('h4', `${group.side === 'incoming' ? '받는 연결' : '보내는 연결'} · ${group.label} ${group.items.length}`)); const chips = element('div', '', 'lm-chips'); for (const item of group.items) { const button = chip(item.id, ui, item.note); if (button) chips.append(button); } block.append(chips); full.append(block); relationBlocks.push(block); }
        main.append(full); const fields = element('dl', '', 'lm-fields'); for (const field of node.fields) { if (!field.value.length) continue; const value = element('dd'); if (typeof field.value === 'string') value.textContent = field.value; else { const values = element('ul'); for (const text of field.value) values.append(element('li', text)); value.append(values); } fields.append(element('dt', field.label), value); } main.append(fields);
        const note = interpretation(node.interpretation); if (note) main.append(note); if (ui.context.nodeHref) main.append(anchor('근거와 전체 속성 보기 ↗', ui.context.nodeHref(node.id)));
        draw = (): void => {
            if (!ego.clientWidth) return; ego.replaceChildren(); if (!node.relationGroups.length) { ego.append(element('p', '다른 콘텐츠와 직접 이어진 연결이 없습니다. 아래 설명을 보세요.', 'lm-empty')); return; }
            const width = Math.max(660, ego.clientWidth - 16), columnWidth = Math.min(214, Math.round(width * .29)); const rowHeight = 40, gap = 7, headingHeight = 22, groupGap = 12;
            const measure = (side: 'incoming' | 'outgoing'): number => node.relationGroups.filter(group => group.side === side).reduce((sum, group) => sum + headingHeight + Math.min(6, group.items.length) * (rowHeight + gap) + (group.items.length > 6 ? 24 : 0) + groupGap, 0);
            const leftHeight = measure('incoming'), rightHeight = measure('outgoing'); const height = Math.max(leftHeight, rightHeight, 116) + 24; const centerX = width / 2, centerY = height / 2, centerWidth = Math.min(250, width - 2 * columnWidth - 120);
            const graph = svg('svg'); graph.setAttribute('width', String(width)); graph.setAttribute('height', String(height)); graph.setAttribute('viewBox', `0 0 ${width} ${height}`); graph.setAttribute('role', 'group'); graph.setAttribute('aria-label', `${node.name} · 왼쪽은 받는 연결, 오른쪽은 보내는 연결`);
            const text = (x: number, y: number, value: string, className: string): SVGTextElement => { const item = svg('text'); item.setAttribute('x', String(x)); item.setAttribute('y', String(y)); item.textContent = value; item.classList.add(className); return item; };
            for (const side of ['incoming', 'outgoing'] as const) {
                const left = side === 'incoming'; const x = left ? 6 : width - 6 - columnWidth; let y = (height - (left ? leftHeight : rightHeight)) / 2;
                for (const [index, group] of node.relationGroups.entries()) {
                    if (group.side !== side) continue; graph.append(text(x, y + 14, group.label, 'lm-ego-label')); y += headingHeight;
                    for (const item of group.items.slice(0, 6)) {
                        const neighbor = ui.byId.get(item.id); if (!neighbor) continue; const subtitle = item.note ?? label(neighbor, ui); const from = left ? x + columnWidth : centerX + centerWidth / 2; const to = left ? centerX - centerWidth / 2 : x; const fromY = left ? y + rowHeight / 2 : centerY; const toY = left ? centerY : y + rowHeight / 2; const middle = (from + to) / 2; const edge = svg('path'); edge.classList.add('lm-ego-edge'); edge.setAttribute('d', `M${from} ${fromY}C${middle} ${fromY} ${middle} ${toY} ${to} ${toY}`); graph.append(edge);
                        const button = svg('g'); button.classList.add('lm-ego-node'); button.setAttribute('role', 'button'); button.setAttribute('tabindex', '0'); button.setAttribute('aria-label', `${neighbor.name} · ${subtitle}${ui.model.showStatus ? ` · ${ui.model.statusLabels[neighbor.status]}` : ''}`); const rect = svg('rect'); for (const [key, value] of Object.entries({ x, y, width: columnWidth, height: rowHeight, rx: 8 })) rect.setAttribute(key, String(value)); const icon = glyph(neighbor); icon.setAttribute('x', String(x + 9)); icon.setAttribute('y', String(y + 12)); const truncate = (value: string, limit: number): string => value.length > limit ? value.slice(0, limit - 1) + '…' : value; const title = svg('title'); title.textContent = `${neighbor.name} · ${subtitle}`;
                        button.append(rect, icon, text(x + 32, y + 17, truncate(neighbor.name, 13), 'lm-ego-name'), text(x + 32, y + 32, truncate(subtitle, 20), 'lm-ego-note'), title); if (neighbor.status === 'present') { const dot = svg('circle'); dot.setAttribute('cx', String(x + columnWidth - 11)); dot.setAttribute('cy', String(y + 11)); dot.setAttribute('r', '3.6'); dot.style.fill = 'var(--lm-live)'; button.append(dot); } const open = (): void => ui.openFocus(neighbor.id); button.addEventListener('click', open); button.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); open(); } }); graph.append(button); y += rowHeight + gap;
                    }
                    if (group.items.length > 6) { const more = text(x, y + 14, `+${group.items.length - 6}개 더 · 아래 목록`, 'lm-ego-more'); more.setAttribute('role', 'button'); more.setAttribute('tabindex', '0'); const open = (): void => { relationBlocks[index]?.scrollIntoView({ block: 'center' }); }; more.addEventListener('click', open); more.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); open(); } }); graph.append(more); y += 24; } y += groupGap;
                }
            }
            const center = svg('g'); center.classList.add('lm-ego-center'); const rect = svg('rect'); for (const [key, value] of Object.entries({ x: centerX - centerWidth / 2, y: centerY - 46, width: centerWidth, height: 92, rx: 12 })) rect.setAttribute(key, String(value)); const icon = glyph(node, 18); icon.setAttribute('x', String(centerX - 9)); icon.setAttribute('y', String(centerY - 36)); const name = text(centerX, centerY + 4, node.name.length > 12 ? node.name.slice(0, 11) + '…' : node.name, 'lm-ego-center-name'); name.setAttribute('text-anchor', 'middle'); const kindText = text(centerX, centerY + 26, label(node, ui), 'lm-ego-note'); kindText.setAttribute('text-anchor', 'middle'); center.append(rect, icon, name, kindText); graph.append(center); ego.append(graph);
        }; draw();
    };
    const observer = new ResizeObserver(() => draw()); observer.observe(main); renderList(); return { select, cleanup: () => observer.disconnect() };
}
