import type { LoopUI } from './loop-map-types.js';
import { element, glyph, interpretation, label, liveDot, media, orderedKinds } from './loop-map-shared.js';

export function renderLoopCatalog(host: HTMLElement, ui: LoopUI): void {
    const tools = element('div', '', 'lm-catalog-tools'); const search = element('input'); search.type = 'search'; search.placeholder = '이름·문구로 찾기'; search.setAttribute('aria-label', '도감에서 찾기');
    const onlyPresent = element('label', '', 'lm-toggle'); const checkbox = element('input'); checkbox.type = 'checkbox'; onlyPresent.append(checkbox, document.createTextNode(`${ui.model.statusLabels.present}만`)); tools.append(search, onlyPresent);
    const filters = element('div', '', 'lm-segments'); filters.setAttribute('role', 'group'); filters.setAttribute('aria-label', '종류 고르기'); const count = element('p', '', 'lm-count'); const cards = element('div', '', 'lm-cards'); host.append(tools, filters, count, cards); let selectedKind = '';
    const render = (): void => {
        filters.replaceChildren(); const kinds = orderedKinds(ui); for (const value of ['', ...kinds]) { const nodes = ui.model.nodes.filter(node => !value || node.kind === value); const button = element('button', '', 'lm-segment'); button.type = 'button'; button.setAttribute('aria-pressed', String(selectedKind === value)); if (value && nodes[0]) button.append(glyph(nodes[0], 13)); button.append(document.createTextNode(`${value ? ui.context.kindLabel?.(value) ?? value : '전체'} ${nodes.length}`)); button.onclick = () => { selectedKind = value; render(); }; filters.append(button); }
        const query = search.value.trim().toLocaleLowerCase(); const nodes = ui.model.nodes.filter(node => (!selectedKind || node.kind === selectedKind) && (!checkbox.checked || node.status === 'present') && (!query || `${node.name} ${node.summary || node.interpretation?.summary || ""}`.toLocaleLowerCase().includes(query))).sort((a, b) => kinds.indexOf(a.kind) - kinds.indexOf(b.kind) || Number(b.status === 'present') - Number(a.status === 'present'));
        count.textContent = `${nodes.length}개${checkbox.checked ? ` · ${ui.model.statusLabels.present}만` : ''}`; cards.replaceChildren(); for (const node of nodes) { const card = element('button', '', 'lm-card'); card.type = 'button'; card.dataset['node'] = node.id; const top = element('span', '', 'lm-card-kind'); top.append(glyph(node, 13), document.createTextNode(label(node, ui))); const dot = liveDot(node, ui); if (dot) top.append(dot); card.append(top); const asset = media(node); if (asset) card.append(asset); card.append(element('b', node.name)); if (node.summary) card.append(element('span', node.summary, 'lm-card-summary')); else if (node.interpretation) { card.append(element('small', `AI 요약${node.interpretation.stale ? ' · 원본 변경됨' : ''}`, 'lm-ai-label'), element('span', node.interpretation.summary, 'lm-card-summary')); } if (node.catalogSummary) card.append(element('span', node.catalogSummary, 'lm-card-relation')); card.onclick = () => ui.openFocus(node.id); const note = interpretation(node.interpretation); if (note) { const title = note.querySelector('summary'); if (title) title.textContent = `AI 요약 근거 ${node.interpretation?.evidence.length ?? 0}곳${node.interpretation?.stale ? ' · 원본 변경됨' : ''}`; const record = element('article', '', 'lm-catalog-record'); record.append(card, note); cards.append(record); } else cards.append(card); } if (!nodes.length) cards.append(element('p', '조건에 맞는 항목이 없습니다.', 'lm-muted'));
    };
    search.oninput = render; checkbox.onchange = render; render();
}
