import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export function verifyHistory(cli, repository) {
  mkdirSync(join(repository, '.lattice'), { recursive: true });
  const git = args => execFileSync('git', ['-C', repository, ...args], { encoding: 'utf8' }).trimEnd();
  const run = args => execFileSync(process.execPath, [cli, ...args, '--root', repository], { encoding: 'utf8' });
  const json = path => JSON.parse(readFileSync(join(repository, path), 'utf8'));
  git(['init', '--quiet']);
  git(['config', 'user.name', 'Lattice verification']);
  git(['config', 'user.email', 'lattice@example.invalid']);
  writeFileSync(join(repository, '.gitignore'), '.lattice/cache/\n.lattice/site/\n');
  const finding = id => ({ id, query: { kinds: ['service'] }, metrics: { count: { op: 'count', value: { op: 'get', from: 'vars', path: ['targets'] } } }, template: '{count} services', gate: { metric: 'count', comparator: 'gte', threshold: 2 } });
  const lens = { schemaVersion: 1, name: 'Service map', kinds: [{ id: 'service', label: 'Service', files: ['*.json'] }], facets: [{ id: 'stage', key: 'stage', value: { op: 'get', from: 'node', path: ['stage'] } }], findings: [finding('count'), finding('old-rule')] };
  const save = (path, value) => writeFileSync(join(repository, path), JSON.stringify(value, null, 2) + '\n');
  save('.lattice/lens.json', lens);
  save('services.json', [{ id: 'service:a', name: 'API', stage: 'draft', targetId: 'service:b' }, { id: 'service:b', name: 'Worker', stage: 'live' }, { id: 'service:keep', targetId: 'service:a' }]);
  git(['add', '.']); git(['commit', '--quiet', '-m', 'Create service map']);
  const beforeCommit = git(['rev-parse', 'HEAD']);
  run(['build']);
  const beforeHash = json('.lattice/cache/graph.json').hash;
  save('services.json', [{ id: 'service:a', name: 'API v2', stage: 'live', targetId: 'service:c' }, { id: 'service:c', name: 'Queue', stage: 'live' }, { id: 'service:keep', targetId: 'service:a' }]);
  lens.findings = [finding('count'), finding('new-rule')];
  lens.findings[0].gate.threshold = 4;
  save('.lattice/lens.json', lens);
  git(['add', '.']); git(['commit', '--quiet', '-m', 'Replace dependency and revise gate']);
  const afterCommit = git(['rev-parse', 'HEAD']);
  const diff = JSON.parse(run(['diff', beforeCommit, '--json']));
  assert.equal(diff.before.commit, beforeCommit);
  assert.equal(diff.after.commit, afterCommit);
  assert.equal(diff.before.graphHash, beforeHash);
  assert.equal(diff.before.coverage, 'repository-lens');
  assert.equal(diff.after.dirty, false);
  assert.deepEqual(diff.nodes.added.map(node => node.id), ['service:c']);
  assert.deepEqual(diff.nodes.removed.map(node => node.id), ['service:b']);
  assert.equal(diff.nodes.changed.find(node => node.id === 'service:a').before.name, 'API');
  assert.equal(diff.nodes.changed.find(node => node.id === 'service:a').after.name, 'API v2');
  for (const key of ['edges', 'facets', 'findings']) {
    assert.ok(diff[key].added.length > 0, `${key} added`);
    assert.ok(diff[key].removed.length > 0, `${key} removed`);
    assert.ok(diff[key].changed.length > 0, `${key} changed`);
  }
  const gateChange = diff.findings.changed.find(entry => entry.id === 'count');
  assert.equal(gateChange.before.gate.status, 'pass');
  assert.equal(gateChange.after.gate.status, 'fail');
  assert.deepEqual(JSON.parse(run(['diff', beforeCommit, '--json'])), diff);
  assert.equal(json('.lattice/cache/snapshots.json').length, 2);
  run(['export', join(repository, '.lattice/site')]);
  for (const snapshot of json('.lattice/site/snapshots.json')) assert.equal(json(`.lattice/site/${snapshot.artifactPath}`).hash, snapshot.graphHash);
  writeFileSync(join(repository, 'note.md'), '# Staged but preserved\n');
  git(['add', 'note.md']);
  writeFileSync(join(repository, 'note.md'), '# Unstaged but preserved\n');
  rmSync(join(repository, 'services.json'));
  save('extra.json', { id: 'service:dirty', name: 'Untracked' });
  const state = git(['status', '--porcelain=v1', '--untracked-files=all']);
  const index = readFileSync(join(repository, '.git/index'));
  const dirty = JSON.parse(run(['diff', beforeCommit, '--json']));
  assert.equal(dirty.after.dirty, true);
  assert.deepEqual(dirty.nodes.added.map(node => node.id), ['service:dirty']);
  assert.equal(git(['status', '--porcelain=v1', '--untracked-files=all']), state);
  assert.deepEqual(readFileSync(join(repository, '.git/index')), index);
  assert.equal(readFileSync(join(repository, 'note.md'), 'utf8'), '# Unstaged but preserved\n');
  assert.equal(json('.lattice/cache/snapshots.json').length, 2);
  rmSync(join(repository, 'extra.json'));
  const emptied = JSON.parse(run(['diff', beforeCommit, '--json']));
  assert.equal(emptied.nodes.removed.length, 3);
  assert.equal(emptied.nodes.added.length, 0);
  assert.equal(spawnSync(process.execPath, [cli, 'diff', 'missing-reference', '--root', repository], { encoding: 'utf8' }).status, 2);
  console.log('Installed history: two commits, all collection deltas, original lens, snapshots/export, deterministic repeat and dirty/index preservation passed.');

  const projection = join(repository, 'projection');
  mkdirSync(projection); execFileSync('git', ['init', '--quiet', projection]);
  writeFileSync(join(projection, 'services.json'), '[{"id":"service:one"}]');
  execFileSync('git', ['-C', projection, 'add', '.']);
  execFileSync('git', ['-C', projection, '-c', 'user.name=Lattice', '-c', 'user.email=lattice@example.invalid', 'commit', '--quiet', '-m', 'Data before lens']);
  mkdirSync(join(projection, '.lattice'));
  writeFileSync(join(projection, '.lattice/lens.json'), JSON.stringify(lens));
  const projected = JSON.parse(execFileSync(process.execPath, [cli, 'diff', 'HEAD', '--root', projection, '--json'], { encoding: 'utf8' }));
  assert.equal(projected.before.coverage, 'current-lens-projection');
  assert.equal(projected.before.lensHash, projected.after.lensHash);
  assert.equal(projected.nodes.added.length + projected.nodes.removed.length + projected.nodes.changed.length, 0);
  console.log('Installed history: missing historical lens explicitly labeled current-lens projection.');
  const empty = join(repository, 'empty');
  mkdirSync(empty); execFileSync('git', ['init', '--quiet', empty]);
  execFileSync('git', ['-C', empty, '-c', 'user.name=Lattice', '-c', 'user.email=lattice@example.invalid', 'commit', '--allow-empty', '--quiet', '-m', 'Empty baseline']);
  writeFileSync(join(empty, 'new.json'), '{"id":"new:record"}');
  const added = JSON.parse(execFileSync(process.execPath, [cli, 'diff', 'HEAD', '--root', empty, '--json'], { encoding: 'utf8' }));
  assert.deepEqual(added.nodes.added.map(node => node.id), ['new:record']);
  console.log('Installed history: empty baseline and removal of all inputs produce real deltas.');
}
