import { verifyInit } from './init-smoke.mjs';
import { verifyYaml } from './yaml-smoke.mjs';
import { verifyExport } from './export-smoke.mjs';
import { verifyServe } from './serve-smoke.mjs';
import { verifyHistory } from './history-smoke.mjs';
import { verifyIncremental } from './incremental-smoke.mjs';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const temporary = mkdtempSync(join(tmpdir(), 'lattice-package-'));
try {
  const packed = JSON.parse(execFileSync('npm', ['pack', '--ignore-scripts', '--json', '--pack-destination', temporary], { cwd: root, encoding: 'utf8' }));
  assert.equal(packed.length, 1);
  const entry = packed[0];
  assert.ok(entry.files.some(file => file.path === 'dist/index.js'));
  assert.ok(entry.files.some(file => file.path === 'dist/index.d.ts'));
  assert.ok(entry.files.every(file => !file.path.startsWith('tests/') && !file.path.startsWith('.omo/')));
  writeFileSync(join(temporary, 'package.json'), JSON.stringify({ private: true, type: 'module' }));
  execFileSync('npm', ['install', '--ignore-scripts', '--no-audit', '--no-fund', join(temporary, entry.filename)], { cwd: temporary, stdio: 'pipe' });
  const manifest = JSON.parse(readFileSync(join(temporary, 'node_modules/@hyunlord/lattice/package.json'), 'utf8'));
  assert.deepEqual(manifest.dependencies, {yaml:'2.9.1'});
  const output = execFileSync(process.execPath, ['--input-type=module', '-e', `
    import assert from 'node:assert/strict';
    import { createHash } from 'node:crypto';
    import { canonicalJson, createGraph, extractJson, extractCsv, resolveRecords } from '@hyunlord/lattice';
    const digest = text => createHash('sha256').update(text).digest('hex');
    assert.equal(canonicalJson({b:2,a:1}), '{"a":1,"b":2}');
    const graph = createGraph({ repository: {name:'installed',dirty:false,sourceFingerprint:digest('empty')},nodes:[],edges:[],facets:[],findings:[],views:[],snapshots:[],lensDigest:null,adapterVersions:{},inputs:[] }, digest);
    assert.match(graph.hash, /^[a-f0-9]{64}$/);
    assert.throws(() => canonicalJson({number:NaN}), {name:'GraphInputError'});
    const text = '[{"id":"a","targetId":"b"},{"id":"b"}]';
    assert.equal(resolveRecords(extractJson({path:'records.json',text,contentHash:digest(text)})).edges.length, 1);
    assert.equal(extractCsv({path:'records.csv',text:'id,name',contentHash:digest('id,name')}).length, 0);
    console.log('Installed ESM exports, graph construction, hash and rejection path passed.');
  `], { cwd: temporary, encoding: 'utf8' });
  console.log(output.trim());
  const help = execFileSync(process.execPath, [join(temporary, 'node_modules/@hyunlord/lattice/bin/lattice.mjs'), '--help'], { cwd: temporary, encoding: 'utf8' });
  assert.match(help, /lattice build/);
  assert.ok(entry.files.some(file => file.path === 'viewer/app.js'));
  assert.equal(manifest.license, 'MIT');
  console.log('Installed CLI launch and static viewer packaging passed.');
  const repository = join(temporary, 'repository');
  mkdirSync(repository);
  execFileSync('git', ['init', '--quiet', repository]);
  writeFileSync(join(repository, 'records.json'), '[{"id":"service:a","name":"API","dependencyId":"service:b"},{"id":"service:b","name":"Worker"}]');
  writeFileSync(join(repository, 'owners.csv'), 'id,name,serviceId\nowner:a,Platform,service:a\n');
  writeFileSync(join(repository, 'README.md'), '# Service map\n[Decision](decision.md#decision)\n');
  writeFileSync(join(repository, 'decision.md'), '# Deployment\n## Status\nAccepted\n## Decision\nUse a worker.\n');
  mkdirSync(join(repository, 'pkg'));
  writeFileSync(join(repository, 'main.ts'), 'import { work } from "./worker.js";\nexport { work } from "./worker.js";\n');
  writeFileSync(join(repository, 'worker.ts'), 'export function work() { return 1; }\n');
  writeFileSync(join(repository, 'pkg/__init__.py'), 'from .worker import work\n');
  writeFileSync(join(repository, 'pkg/worker.py'), 'import json\ndef work(): return 1\n');
  writeFileSync(join(repository, 'job.py'), 'from pkg import worker\nimport pkg.worker as worker_alias\n');
  writeFileSync(join(repository, 'Worker.cs'), 'public class Worker {}\n');
  const cli = join(temporary, 'node_modules/@hyunlord/lattice/bin/lattice.mjs');
  const run = args => execFileSync(process.execPath, [cli, ...args, '--root', repository], {encoding:'utf8'});
  run(['build']);
  const graphPath = join(repository, '.lattice/cache/graph.json');
  const first = JSON.parse(readFileSync(graphPath, 'utf8'));
  assert.equal(first.lensDigest, null);
  assert.equal(first.edges.filter(edge => edge.kind === 'imports').length, 5);
  assert.ok(first.edges.some(edge => edge.source === 'module:pkg/__init__.py' && edge.target === 'module:pkg/worker.py'));
  assert.equal(first.nodes.find(node => node.id === 'module:Worker.cs').attributes.extraction, 'file-only');
  assert.ok(first.edges.some(edge => edge.source === 'owner:a' && edge.target === 'service:a'));
  assert.ok(first.edges.some(edge => edge.kind === 'link' && edge.target === 'document:decision.md#decision'));
  assert.equal(first.nodes.find(node => node.id === 'document:decision.md').attributes.status, 'Accepted');
  run(['build']);
  assert.equal(JSON.parse(readFileSync(graphPath, 'utf8')).hash, first.hash);
  const site = join(temporary, 'site');
  run(['export', site]);
  assert.equal(JSON.parse(readFileSync(join(site, 'graph.json'), 'utf8')).hash, first.hash);
  console.log('Installed zero-config JSON/CSV/Markdown/code build, cross-file references, ADR metadata, deterministic rebuild and export passed.');
  const lens = { schemaVersion: 1, name: 'Service coverage', kinds: [{id:'service',label:'Service',files:['records.json']}], findings: [{id:'service-count',query:{kinds:['service']},metrics:{count:{op:'count',value:{op:'get',from:'vars',path:['targets']}}},template:'Services: {count}',gate:{metric:'count',comparator:'eq',threshold:2}}] };
  const lensPath = join(repository, '.lattice/lens.json');
  const saveLens = () => writeFileSync(lensPath, JSON.stringify(lens));
  const check = () => spawnSync(process.execPath, [cli,'check','--root',repository], {encoding:'utf8'});
  saveLens();
  assert.equal(check().status, 0);
  assert.equal(JSON.parse(readFileSync(graphPath,'utf8')).findings[0].gate.status, 'pass');
  writeFileSync(join(repository, 'records.json'), '[{"id":"service:a","name":"API"}]');
  assert.equal(check().status, 1);
  assert.equal(JSON.parse(readFileSync(graphPath,'utf8')).findings[0].gate.status, 'fail');
  lens.findings[0].metrics.count = {op:'get',from:'vars',path:['missing']};
  saveLens();
  assert.equal(check().status, 1);
  assert.equal(JSON.parse(readFileSync(graphPath,'utf8')).findings[0].gate.status, 'unknown');
  lens.findings[0].gate.threshold = 'two';
  saveLens();
  assert.equal(check().status, 2);
  console.log('Installed check: pass=0, edited input fail=1, unknown evidence=1, invalid config=2.');
  verifyInit(cli, join(temporary, 'init'));
  verifyYaml(cli, join(temporary, 'yaml'));
  verifyHistory(cli, join(temporary, 'history'));
  verifyIncremental(cli, join(temporary, 'incremental'));
  verifyExport(cli, join(temporary, 'export'));
  await verifyServe(cli, join(temporary, 'serve'));
} finally { rmSync(temporary, { recursive: true, force: true }); }
