export const schemaVersion = 1;
export { canonicalJson } from "./core/canonical.js";
export type { JsonValue, JsonObject } from "./core/canonical.js";
export { GraphInputError } from "./core/errors.js";
export { createGraph } from "./core/graph.js";
export { diffGraphs } from "./core/diff.js";
export type { GraphDiff, RecordDiff, RecordChange } from "./core/diff.js";
export type { Source, NodeDraft, Node, Edge, Facet, Finding, View, InputDigest, Snapshot, Repository, GraphDraft, Graph, Digest } from "./core/model.js";
export { DataInputError } from "./adapters/types.js";
export type { SourceInput, ExtractedRecord } from "./adapters/types.js";
export { extractYaml, extractYamlDocument } from "./adapters/yaml.js";
export { extractJson } from "./adapters/json.js";
export { extractCsv } from "./adapters/csv.js";
export { resolveRecords } from "./adapters/resolve.js";
export type { ReferenceDiagnostic, ResolvedRecords } from "./adapters/resolve.js";
export { parseLens, matchesGlob, applyLens } from "./lens/index.js";
export type { Lens, LensKind } from "./lens/index.js";
export { extractMarkdown } from "./adapters/markdown.js";
export type { MarkdownDocument, DocumentLink } from "./adapters/markdown.js";
export { resolveDocumentLinks } from "./adapters/document-links.js";
export type { LinkedDocuments, DocumentDiagnostic } from "./adapters/document-links.js";
export { extractCode, codeLanguage } from "./adapters/code.js";
export type { CodeModule, ModuleImport } from "./adapters/code.js";
export { resolveModuleLinks } from "./adapters/module-links.js";
export type { ModuleDiagnostic } from "./adapters/module-links.js";
export { importGraft, graftAdapterVersion } from "./adapters/graft.js";
export type { GraftImport, GraftDiagnostic } from "./adapters/graft.js";
export { automaticFindings } from "./core/automatic-findings.js";
export type { AutomaticDiagnostic } from "./core/automatic-findings.js";
export { codeStructure } from "./adapters/code-structure.js";
